name: Build Test Deploy

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build the app image
      uses: docker/build-push-action@v4
      with:
        push: false
        context: .
        file: ./Dockerfile
        platforms: | 
          linux/amd64
          linux/arm64

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the app image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: conzorkingkong/conazon-products:test
        
      - name: Run tests in Docker container
        run: docker run --rm conzorkingkong/conazon-products:test go test ./...
  
  deploy-latest:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: | 
            linux/amd64
            linux/arm64
          tags: conzorkingkong/conazon-products:latest
  
  deploy-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: | 
            linux/amd64
            linux/arm64
          tags: conzorkingkong/conazon-products:dev